### ISSUE TITLE
pip install meinheld error

### ISSUE THREAD

**Issue by namenameshuai** [mopemope/meinheld#114]
OS version：centos 7.5 or centos 6.8
Python version：Python3.6

Requirement already satisfied: greenlet<0.5,>=0.4.5 in ./.venv/lib/python3.6/site-packages (from meinheld) (0.4.15)
Building wheels for collected packages: meinheld
  Building wheel for meinheld (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /app/python_test/.venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h22lxwt_ --python-tag cp36
       cwd: /tmp/pip-install-s7rdks_2/meinheld/
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/mlogging.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/msocket.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/gmeinheld.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/middleware.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/common.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/__init__.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/patch.py -> build/lib.linux-x86_64-3.6/meinheld
  copying meinheld/websocket.py -> build/lib.linux-x86_64-3.6/meinheld
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building 'meinheld.server' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/meinheld
  creating build/temp.linux-x86_64-3.6/meinheld/server
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/response.c -o build/temp.linux-x86_64-3.6/meinheld/server/response.o
  meinheld/server/response.c: In function ‘writev_bucket’:
  meinheld/server/response.c:293:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     Py_END_ALLOW_THREADS if (w == -1) {
                                ^
  meinheld/server/response.c:311:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (; i < data->iov_cnt; i++) {
                  ^
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/time_cache.c -o build/temp.linux-x86_64-3.6/meinheld/server/time_cache.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/heapq.c -o build/temp.linux-x86_64-3.6/meinheld/server/heapq.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/buffer.c -o build/temp.linux-x86_64-3.6/meinheld/server/buffer.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/timer.c -o build/temp.linux-x86_64-3.6/meinheld/server/timer.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/http_parser.c -o build/temp.linux-x86_64-3.6/meinheld/server/http_parser.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/request.c -o build/temp.linux-x86_64-3.6/meinheld/server/request.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/util.c -o build/temp.linux-x86_64-3.6/meinheld/server/util.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/input.c -o build/temp.linux-x86_64-3.6/meinheld/server/input.o
  meinheld/server/input.c:229:20: warning: ‘file_getsetlist’ defined but not used [-Wunused-variable]
   static PyGetSetDef file_getsetlist[] = {
                      ^
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/log.c -o build/temp.linux-x86_64-3.6/meinheld/server/log.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/server.c -o build/temp.linux-x86_64-3.6/meinheld/server/server.o
  meinheld/server/server.c: In function ‘unix_listen’:
  meinheld/server/server.c:1368:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (len >= sizeof(saddr.sun_path)) {
             ^
  meinheld/server/server.c: At top level:
  meinheld/server/server.c:160:13: warning: ‘destroy_pendings’ defined but not used [-Wunused-function]
   static void destroy_pendings(void) {
               ^
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/http_request_parser.c -o build/temp.linux-x86_64-3.6/meinheld/server/http_request_parser.o
  meinheld/server/http_request_parser.c: In function ‘check_field_name’:
  meinheld/server/http_request_parser.c:548:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < len; i++) {
     ^
  meinheld/server/http_request_parser.c:548:3: note: use option -std=c99 or -std=gnu99 to compile your code
  meinheld/server/http_request_parser.c:548:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < len; i++) {
                       ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for meinheld
  Running setup.py clean for meinheld
Failed to build meinheld
Installing collected packages: meinheld
    Running setup.py install for meinheld ... error
    ERROR: Command errored out with exit status 1:
     command: /app/python_test/.venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-82xjofz7/install-record.txt --single-version-externally-managed --compile --install-headers /app/python_test/.venv/include/site/python3.6/meinheld
         cwd: /tmp/pip-install-s7rdks_2/meinheld/
    Complete output (60 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/mlogging.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/msocket.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/gmeinheld.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/middleware.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/common.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/__init__.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/patch.py -> build/lib.linux-x86_64-3.6/meinheld
    copying meinheld/websocket.py -> build/lib.linux-x86_64-3.6/meinheld
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'meinheld.server' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/meinheld
    creating build/temp.linux-x86_64-3.6/meinheld/server
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/response.c -o build/temp.linux-x86_64-3.6/meinheld/server/response.o
    meinheld/server/response.c: In function ‘writev_bucket’:
    meinheld/server/response.c:293:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       Py_END_ALLOW_THREADS if (w == -1) {
                                  ^
    meinheld/server/response.c:311:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (; i < data->iov_cnt; i++) {
                    ^
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/time_cache.c -o build/temp.linux-x86_64-3.6/meinheld/server/time_cache.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/heapq.c -o build/temp.linux-x86_64-3.6/meinheld/server/heapq.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/buffer.c -o build/temp.linux-x86_64-3.6/meinheld/server/buffer.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/timer.c -o build/temp.linux-x86_64-3.6/meinheld/server/timer.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/http_parser.c -o build/temp.linux-x86_64-3.6/meinheld/server/http_parser.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/request.c -o build/temp.linux-x86_64-3.6/meinheld/server/request.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/util.c -o build/temp.linux-x86_64-3.6/meinheld/server/util.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/input.c -o build/temp.linux-x86_64-3.6/meinheld/server/input.o
    meinheld/server/input.c:229:20: warning: ‘file_getsetlist’ defined but not used [-Wunused-variable]
     static PyGetSetDef file_getsetlist[] = {
                        ^
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/log.c -o build/temp.linux-x86_64-3.6/meinheld/server/log.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/server.c -o build/temp.linux-x86_64-3.6/meinheld/server/server.o
    meinheld/server/server.c: In function ‘unix_listen’:
    meinheld/server/server.c:1368:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (len >= sizeof(saddr.sun_path)) {
               ^
    meinheld/server/server.c: At top level:
    meinheld/server/server.c:160:13: warning: ‘destroy_pendings’ defined but not used [-Wunused-function]
     static void destroy_pendings(void) {
                 ^
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_GREENLET -DHTTP_PARSER_DEBUG=0 -I/opt/python/python36/include/python3.6m -c meinheld/server/http_request_parser.c -o build/temp.linux-x86_64-3.6/meinheld/server/http_request_parser.o
    meinheld/server/http_request_parser.c: In function ‘check_field_name’:
    meinheld/server/http_request_parser.c:548:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < len; i++) {
       ^
    meinheld/server/http_request_parser.c:548:3: note: use option -std=c99 or -std=gnu99 to compile your code
    meinheld/server/http_request_parser.c:548:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < len; i++) {
                         ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /app/python_test/.venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s7rdks_2/meinheld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-82xjofz7/install-record.txt --single-version-externally-managed --compile --install-headers /app/python_test/.venv/include/site/python3.6/meinheld Check the logs for full command output.

**Comment by mmyjona** [comment]
it's fixed in master. wait for new release or install from master or downgrade to 1.0.1.

**Comment by namenameshuai** [comment]
ok,thx.

**Comment by namenameshuai** [comment]
> it's fixed in master. wait for new release or install from master or downgrade to 1.0.1.
ok,thx,I didn't find this message
