### ISSUE TITLE
cant start meinheld with pypy 

### ISSUE THREAD

**Issue by sachet-foundation** [mopemope/meinheld#121]
I  am trying to use gunicorn with meinheld on a pypy3 flask interpreter. 
  1. would you recommend this architecture?
  2. am facing this issue - could you help me what i have to do?

```
File "/opt/pypy/site-packages/meinheld/__init__.py", line 1, in <module>
    from meinheld.server import *
ImportError: /opt/pypy/site-packages/meinheld/server.pypy37-pp73-x86_64-linux-gnu.so: undefined symbol: PyFile_FromFd
```

I have installed the following packages
```
apt-get update && apt-get install -y \
apt-utils \
gcc \
nginx \
supervisor \
python3-pip \
build-essential \
curl \
zlib1g-dev \
libbz2-dev \
python3-dev \
python3.7-dev \
python-dev \ 
libffi-dev \ 
libevent-dev \
libssl-dev \ 
libgc-dev \
liblzma-dev \
python-gevent \ 
apt-file \
&& rm -rf /var/lib/apt/lists/*```

**Comment by mattip** [comment]
I don't see pypy3-dev in the list of packages. I would recommend using conda to get started since the error message indicates you are trying to use a CPython package in PyPy. PyPy's equivalent symbol would be `PyPyFile_FromFd`.

**Comment by sachet-foundation** [comment]
i did try `pypy3-dev` too but it did not work for me @mattip

**Comment by mattip** [comment]
Ahh sorry, my bad. It turns out PyPy does not implement `PyFile_FromFd`. CPython removed `PyFile_FromFile` in version 3.0 and replaced it with `PyFile_FromFd`, and PyPy did not made that transition. I implemented it just now and it will be part of the upcomoning release. 

With that, I am not sure PyPy will be any faster since going to the C-API really slows it down, but at least once that change goes in you should be able to benchmark.

**Comment by jenstroeger** [comment]
Hmph… I didn’t find any mention concerning `FromFile` or `FromFd` in [PyPy’s issue tracker](https://foss.heptapod.net/pypy/pypy/-/issues) 🤔

> PyPy did not made that transition.

Uhm… hmph again, I wonder why they’ve decided not to be [compatible](https://www.pypy.org/compat.html) here.

**Comment by sachet-foundation** [comment]
thanks @jenstroeger - seems like @mattip added it [here](https://foss.heptapod.net/pypy/pypy/-/commit/9e875c961dbb6a99a87b7a6f99994d0b8f8d8f1a)

@mattip thanks - which version does this go online?

**Comment by mattip** [comment]
It should be available soonish in the [nightly builds](http://buildbot.pypy.org/nightly/py3.7/) and I plan on finishing a release by the end of the month. 

I tried out the script at the top of https://meinheld.org/, but I get an error when serving the "hello world" app `TypeError: response item must be a string`. The gunicorn demo fails with `ModuleNotFoundError: No module named 'gunicorn_test'` Are those expected errors or are there further problems with PyPy?

**Comment by maverik-akagami** [comment]
i think that is a meinheld issue - see [here](https://github.com/mopemope/meinheld/blob/6ddb22b52783d22ba15c6cdfbcbc9ed05b5c0c46/example/gunicorn_test.py#L9)

**Comment by mattip** [comment]
Thanks.
