### ISSUE TITLE
psycopg2 async hook

### ISSUE THREAD

**Issue by knappador** [mopemope/meinheld#17]
There's a pyscogreen module for installing a greenlet compatible function into pyscopg2 to get DB queries to run asynchronously.  Because it's gevent (and libevent) it seems that meinheld would need it's own async monkey-patcher for pyscopg2.  Just bringing it up.

**Comment by dnp1** [comment]
@mopemope  Can you help me implement a "SemaphorePool", I'm fixing several issues and  proposing a dockerized banchmark based on https://github.com/calpaterson/python-web-perf

here: https://github.com/dnp1/python-web-perf


However I'm facing some difficult to implement database pool who waits from available connection (like I could for gevent)


A simple Semaphore between co-routines would be great

**Comment by dnp1** [comment]
I could use eventlet Semaphore and it worked
