### ISSUE TITLE
Crash in server.c

### ISSUE THREAD

**Issue by bulletmark** [mopemope/meinheld#65]
Not sure whether/how meinheld is related but I'll post here to get a comment. I have been using meinheld happily for years for my home alarm system running on a raspberry pi. Some time ago I ported to Arch on a RPi2. Today I saw a core dump which I believe may be related to the relatively recent upgrade on Arch from python 3.4 to python 3.5:
```
pi@pi3:~ coredumpctl --no-pager info 
           PID: 220 (python)
           UID: 1000 (pi)
           GID: 1000 (pi)
        Signal: 11 (SEGV)
     Timestamp: Wed 2015-12-02 05:10:32 AEST (6h ago)
  Command Line: env/bin/python pialarm
    Executable: /usr/bin/python3.5
 Control Group: /user.slice/user-1000.slice/user@1000.service/pialarm.service
          Unit: user@1000.service
         Slice: user-1000.slice
     Owner UID: 1000 (pi)
       Boot ID: bcca24ad226540f8a6a397a9dc33ff85
    Machine ID: 663f6cee40174da8ab551172a29af2b2
      Hostname: pi3
      Coredump: /var/lib/systemd/coredump/core.python.1000.bcca24ad226540f8a6a397a9dc33ff85.220.1448997032000000.lz4
       Message: Process 220 (python) of user 1000 dumped core.
                
                Stack trace of thread 220:
                #0  0x0000000075428ec8 parse_http_request (server.cpython-35m-arm-linux-gnueabihf.so)
                #1  0x0000000075429094 read_callback (server.cpython-35m-arm-linux-gnueabihf.so)
                #2  0x00000000754347c8 picoev_poll_once_internal (server.cpython-35m-arm-linux-gnueabihf.so)
                #3  0x000000007542b4e4 picoev_loop_once (server.cpython-35m-arm-linux-gnueabihf.so)
                #4  0x0000000076d70068 PyCFunction_Call (libpython3.5m.so.1.0)
```

Presumably this may be due to greenlet? I see that meinheld requires specific greenlet version 0.4.5 although 0.4.9 is on PyPI. Any reason it can't use the most update to date package?

**Comment by methane** [comment]
>  I see that meinheld requires specific greenlet version 0.4.5 although 0.4.9 is on PyPI. 

meinheld should accept greenlet 0.4.9.

https://github.com/mopemope/meinheld/blob/master/setup.py#L73
```
    install_requires=['greenlet>=0.4.5,<0.5']
```

There was refcount bug in greenlet which is fixed at 0.4.5.
meinheld had managed the bug before. So old meinheld requires greenlet<0.4.5 and
current meinheld requires greenlet>=0.4.5.

ref: https://github.com/mopemope/meinheld/commit/bf601c1df34d3007c7f7d487d55115250a808f9f

**Comment by bulletmark** [comment]
OK, I was confused by the README at https://pypi.python.org/pypi/meinheld/0.5.8 which says it requires greenlet == 0.4.5. So it turns out I am actually using greenlet 0.4.9. So does it seem that is where the bug will be?

**Comment by methane** [comment]
Could you reproduce the crash easily?
If you have binary with debug symbols, could you identify which line of parse_http_request cause segfault?

**Comment by bulletmark** [comment]
My pure python app runs 24x7 but this is the only crash I have ever seen. No idea how to reproduce it. I installed gdb on my pi and then I get the following:
```
core was generated by `env/bin/python pialarm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  parse_http_request (fd=<optimized out>, r=4, buf=0x7eaf65ec "", client=0x1154958) at meinheld/server/server.c:1144
```
So we see the bug is actually in meinheld, not greenlet and in fact at line 1144 of server.c (current master/0.5.8). If you look at that line and the next line, the bug is obvious. The second line 1145 checks *req* for NULL but *req* is dereferenced in the line 1144 before.

Will I fix this and send a pull request?

**Comment by bulletmark** [comment]
I made a patch http://pastebin.com/pQMsFTNL to meinheld which I am now running with my app.

**Comment by methane** [comment]
thanks!

**Comment by bulletmark** [comment]
Don't forget to also remove the incorrect *greenlet == 0.4.5* statement in README.rst as I mentioned in https://github.com/mopemope/meinheld/issues/65#issuecomment-161158006 above. Version dependencies are defined in the metadata, they should not also be hard-coded in a README.

**Comment by bulletmark** [comment]
The current release (0.5.8 on PyPI) still does not include the fix for this bug yet it is quite a serious problem. Would it be possible to do a new release?

**Comment by methane** [comment]
Ping @mopemope

**Comment by mopemope** [comment]
@bulletmark @methane 
Just release 0.5.9. Thanks !
https://pypi.python.org/pypi/meinheld/0.5.9
