### ISSUE TITLE
multiple simultaneous requests

### ISSUE THREAD

**Issue by kianxineki** [mopemope/meinheld#71]
He was performing a test with meinheld, I was trying to test whether it is possible to address several requests at once. I see that the server listens only 1 to 1.

Is there any way to change this? I would like the requests received have the same context and not try a fork process.

I tried to use gunicorn + meinheld, now if I can handle several at a time, but do not share memory for me is a problem. I tried to put --threads 10, but to indicate that parameter only serves 1 to 1

``` python
from bottle import run, get
import time


@get("/test_yield")
def test_yield():
    print("init test_yield")
    for x in range(10):
        time.sleep(1)
        yield(str(x))
    print("end test_yield")

if __name__ == "__main__":
    run(server="meinheld", port="9876", host="0.0.0.0")

```

```
init test_yield
end test_yield
"127.0.0.1 - - [30/Jun/2016:11:32:59 +0000] "GET /test_yield HTTP/1.1" 200 10 "-" "Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5"
init test_yield
end test_yield
"127.0.0.1 - - [30/Jun/2016:11:33:09 +0000] "GET /test_yield HTTP/1.1" 200 10 "-" "Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5"
```

**Comment by methane** [comment]
While meinheld supports greenlet, I think prefork is better way for most use cases.
I think gunicorn + meinheld behind nginx is the best practice you should consider first.

> but do not share memory for me is a problem.

Why?  How many processes do you use?  What is your app's bottleneck? (instead of `time.sleep()`).

**Comment by kianxineki** [comment]
I need to have a list of users connected by websocket to be able to broadcast to everyone. For this I need everyone to have the same context

**Comment by methane** [comment]
You shouldn't use meinheld's websocket.
It is very experimental and based on old spec.

**Comment by methane** [comment]
asyncio or Tornado is what you should use.

**Comment by kianxineki** [comment]
I tried Gevent, is quite similar to meinheld and if I get the part concurrency. I am sorry not to use meinheld :(

**Comment by kianxineki** [comment]
from meinheld import patch
patch.patch_all()

solved :)
