### ISSUE TITLE
Memory leak when using meinheld as gunicorn worker

### ISSUE THREAD

**Issue by admiralobvious** [mopemope/meinheld#72]
Hello,

I have an application that I recently switched from gunicorn+gevent workers to gunicorn+meinheld and it is now having memory leak issues. The issues disappear when I switch back to gevent.

I haven't done much investigation at the moment because I am busy with work, but I plan on doing it later this week. Is there anything in particular I should look for to see if this is really related to meinheld?

I am using the following meinheld-related packages in the application:

```
greenlet==0.4.10
gunicorn==19.6.0
meinheld==0.5.9
```

and the following gunicorn config:

```
bind = '0.0.0.0:5000'
workers = 1 if current_env == 'DEV' else multiprocessing.cpu_count() * 2 + 1
worker_class = 'egg:meinheld#gunicorn_worker'
proc_name = 'api'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" "%({X-Real-IP}i)s" %(L)s'
accesslog = '-'
errorlog = '-'
```

The application is basically a more complex version of this: https://github.com/admiralobvious/falcon-boilerplate

Thank you!

**Comment by georgeyz** [comment]
I haved the same pproblem. Who could help me?
