### ISSUE TITLE
``meinheld.patch.patch_all()`` does not patch ``threading.local``

### ISSUE THREAD

**Issue by defnull** [mopemope/meinheld#73]
Some frameworks (e.g. Bottle and Flask) and maybe applications depend on `threading.local` for context-local storage. `meinheld.patch.patch_all()` does not provide a patch for `threading.local` and therefor is not enough to get these frameworks to work properly.

See https://github.com/bottlepy/bottle/issues/896 for an example.

**Comment by ydf** [comment]
mopemope commented on 20 Jan 2011

meiheled is designed very simple, It work single thread.And meinheld is not thread safe.
If you want to run task a long time, you're increase the number of processes.

**Comment by defnull** [comment]
Your quote is not related to this issue.

**Comment by methane** [comment]
FYI, meinheld doesn't patch threading too.
So meinheld works nice with bottle and Flask unless you use greenlet (async io) feature of meinheld.

I am not interested in meinheld's greenlet feature, because I use asyncio or golang when I need async.
So I recommend you to use gevent.

**Comment by methane** [comment]
Oh, I may wrong. Flask uses `greenlet.get_ident()`.
See https://github.com/pallets/werkzeug/blob/master/werkzeug/local.py

So Flask may works with meinheld even if you use async I/O feature.

**Comment by defnull** [comment]
Are greenlet (async io) features optional? What happens if I read from `environ['wsgi.input']`? is that a blocking operation by default?

**Comment by methane** [comment]
By default, request body is written into tmpfile or on memory buffer.
After whole body is received, wsgi handler is called.
So reading from `environ['wsgi.input']` is on memory operation, or reading from file (blocking).
greenlet switch won't happen during reading from it.

**Comment by defnull** [comment]
Okay, so why does `meinehld.patch.patch_all()`, which only patches `socket`, then causes a thread-change mid request as demonstrated here: https://github.com/bottlepy/bottle/issues/896 ?

**Comment by defnull** [comment]
Ahh okay, because @kianxineki started an outgoing HTTP request while handling a bottle request, this using a socket, which suspended the greenlet and caused the issue. Okay, I understand now.
