### ISSUE TITLE
Encode error with Unicode urls

### ISSUE THREAD

**Issue by 0nkery** [mopemope/meinheld#75]
I am using Meinheld as Gunicorn worker for Django project. Setup is working on Python 3.5 under Ubuntu 16.04. Nginx is running as reverse proxy for Gunicorn.

Django [tries](https://github.com/django/django/blob/master/django/core/handlers/wsgi.py#L213) to encode urls from `utf-8` to `latin-1` (ISO_8859_1) and fails.

I have tried to reproduce this error with Django's devserver and with Gunicorn default worker. Both doesn't have described problem.

Package versions:
```
meinheld (0.6.0)
gunicorn (19.6.0)
Django (1.10.2)
```

**Comment by methane** [comment]
I can't get what you said.
Can you provide minimum reproducible example?

> Django tries to encode urls from utf-8 to latin-1 (ISO_8859_1) and fails.

The code in link seems about decoding, not encoding.

**Comment by 0nkery** [comment]
Consider url like `example.com/documents/документ.txt`.

Django is failing to encode `PATH_INFO` value to `ISO_8859_1` with Meinheld as Gunicorn worker.

**Comment by 0nkery** [comment]
Read the [comment](https://github.com/django/django/blob/master/django/core/handlers/wsgi.py#L213) before `return` statement. Seems like Django expects non-ASCII characters in url to be encoded in `latin-1`. 

Looking at Meinheld sources, namely [here](https://github.com/mopemope/meinheld/blob/master/meinheld/server/http_request_parser.c#L357), looks like Meinheld passes already `utf-8` encoded string (I can be wrong).

**Comment by methane** [comment]
You're right. Thanks.

**Comment by 0nkery** [comment]
Thanks!

PS. What about a patch release?

**Comment by mopemope** [comment]
@0nkery It is already released at 0.6.1. thanks.
