### ISSUE TITLE
did not support python 3.6

### ISSUE THREAD

**Issue by pc10201** [mopemope/meinheld#81]
t.py

from meinheld import server

def hello_world(environ, start_response):
    status = b'200 OK'
    res = b"Hello world!"
    response_headers = [('Content-type', 'text/plain'), ('Content-Length', str(len(res)))]
    start_response(status, response_headers)
    return [res]

server.listen(("0.0.0.0", 8000))
server.run(hello_world)

python t3.py(with pyenv and python 3.6.0)

python t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    from meinheld import server
  File "/tmp/jj/lib/python3.6/site-packages/meinheld/__init__.py", line 1, in <module>
    from meinheld.server import *
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by methane** [comment]
did you used --enable-shared configure option?

It's your job that teach .so file path to Python.

2017/02/22 午後10:46 "刘杨" <notifications@github.com>:

**Comment by pc10201** [comment]
OK.I fixed it.
use this.
```
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.0
```

**Comment by MohamadZeina** [comment]
> ```
> env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.0
> ```

Which file does this go in?
