### ISSUE TITLE
Broken pipe error when serving responses from Django's syndication framework

### ISSUE THREAD

**Issue by pmac** [mopemope/meinheld#98]
We have this problem with [kitsune](https://github.com/mozilla/kitsune/issues/3017) (the project for support.mozilla.org). The stack is:

* Django 1.8.15
* Gunicorn 19.7.1
* Greenlet 0.4.12
* Meinheld 0.6.1 (as Gunicorn worker)

The problem seems to be that [Django's built-in syndication framework](https://github.com/django/django/blob/6a0dc2176f4ebf907e124d433411e52bba39a28e/django/contrib/syndication/views.py#L38-L51) treats the `HttpResponse` object like a writable file descriptor (which it's meant to be) which means the response content is actually a list of strings in the order in which they were written. Calling `response.content` is a [property method that joins the list into a string](https://github.com/django/django/blob/6a0dc2176f4ebf907e124d433411e52bba39a28e/django/http/response.py#L354). This response object works fine in all other WSGI servers I tested but Meinheld seems to lose the file descriptor, send a broken pipe error, and the response ends up being 0 length.

We've solved this for now by manually squashing the list of strings in the response to a single string, but this is merely a work around and not a real fix. I decided to file an issue in case anyone else has this problem and is as confused by it as we were. I'm not sure where the issue is in Meinheld, but perhaps some WSGI expert here can steer us in the right direction. I'm happy to file a pull-request but so far I've not been able to find the bug in the code.

**Comment by methane** [comment]
Sorry, I don't use Django and I don't know what kitsune is and how Dajngo's HttpResponse works.
Would you explain your problem on WSGI layer?

**Comment by methane** [comment]
If you can't explain, you can create very minimal Django application which reproduce your issue.

I don't want use my time and energy for learning Django, syndication framework, and understand what you said.

**Comment by wang4035wei** [comment]
这个问题没有人遇到吗  使用gevent模式没有问题，使用meinheld就报错！

**Comment by NullYing** [comment]
> 这个问题没有人遇到吗 使用gevent模式没有问题，使用meinheld就报错！

遇到了，不过我是用flask的，socket中断的话，就会引发这个报错，在上传的文件的时候比较容易重现
